My Name:      Jack Betteridge
Bug Name:     Recursive MPI calls and pytest
Solution:     This bug was not resolved!
              We just didn't run any parallel tests.
              O_O
